# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Scraper-Yahoo360
version:      0.09
version_from: lib/WWW/Scraper/Yahoo360.pm
installdirs:  site
requires:
    Date::Parse:                   0
    File::Slurp:                   0
    HTTP::Date:                    0
    JSON::XS:                      0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
